name: apstools-test-environment

channels:
  - aps-anl-tag
  - conda-forge
  - defaults

dependencies:
  - python >=3.8, <=3.11
  - area-detector-handlers
  - bluesky >=1.6.7
  - databroker =1.2.5
  - databroker-pack
  - h5py
  - intake
  - matplotlib-base
  - mongoquery >=1.3.6
  - openpyxl
  - ophyd >=1.6.1
  - pandas
  - pint
  - pip
  - prompt-toolkit
  - psutil
  - pydata-sphinx-theme
  - pyEpics >=3.4.3
  - pymongo
  - pyqt =5
  - pyRestTable >=2020.0.8
  - pysumreg
  - qt =5
  - readline !=8.1.2
  - setuptools-scm
  - spec2nexus
  - sphinx >=5

  # - aps-dm-api >=5   # linux-64  osx-64

  # - pip:
    # - bluesky_live
    # - ipython-genutils==0.2.0
    # - prompt-toolkit==1.0.15
